blog_list:
    path:     /blog
    controller: App\Controller\DefaultController::list

blog_show:
    path:     /blog/{id}
    controller: App\Controller\DefaultController::show

test:
    path:     /test/test/test
    controller: App\Controller\DefaultController::list
